# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt full-upgrade -y && sudo apt install -y libegl1 libxkbcommon-x11-0 libxcb-cursor0 libxcb-xinerama0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinput0 libxcb-shape0 libxcb-shm0 libxcb1 libx11-xcb1 libqt6gui6 libqt6widgets6 qt6-base-dev libglib2.0-0 build-essential python3-dev python3-pip python3-venv libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev libpq-dev libjpeg-dev libfreetype6-dev libblas-dev liblapack-dev gfortran libpng-dev x11-apps xvfb
        pip install flake8 pytest
        python -m pip install --upgrade pip
        pip uninstall pycrypto
        pip install -r requirements.txt
        python -m spacy download en_core_web_sm
  
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test using normal run
      run: |
        export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt6/plugins/platforms/
        QT_DEBUG_PLUGINS=1 python app.py

